import pandas as pd
import matplotlib.pyplot as plt

# File path to the CSV file generated by Arduino
file_path = 'NmSec.csv'

# Read the CSV file into a DataFrame
df = pd.read_csv(file_path)

# Check the first few rows of the DataFrame to ensure it's read correctly
print(df.head())

# Convert time into seconds for the x-axis
df['Time (s)'] = df['Time (m)'] * 60 + df['Time (s)']

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(df['Time (s)'], df['Torque (N·m)'], marker='o', linestyle='-', color='b')
plt.xlabel('Time (s)')
plt.ylabel('Torque (N·m)')
plt.title('Torque Over Time')
plt.grid(True)

# Save the plot to a file
plt.savefig('torque_over_time.png')

# Display the plot
plt.show()
